#!/usr/bin/env bash
# =============================================================================
# Cloud Agent environment bootstrap for Apachiy TV (Android).
#
# Idempotent: safe to run repeatedly. Installs the Android SDK, generates a
# local dev signing keystore, and writes a gitignored local.properties so
# `./gradlew :app:assembleFullDebug` works out of the box.
#
# System deps (JDK) come from the base image. This project builds and tests
# identically on the preinstalled JDK 21 and on JDK 17 (the version pinned by
# CI and README-APACHIY).
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

ANDROID_HOME="${ANDROID_HOME:-$HOME/android-sdk}"
CMDLINE_TOOLS_ZIP="commandlinetools-linux-15859902_latest.zip"
COMPILE_SDK="platforms;android-36"
BUILD_TOOLS="build-tools;36.0.0"

echo "==> [1/4] Android SDK command-line tools"
if [ ! -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
  mkdir -p "$ANDROID_HOME/cmdline-tools"
  tmp="$(mktemp -d)"
  curl -fsSL -o "$tmp/cmdtools.zip" \
    "https://dl.google.com/android/repository/${CMDLINE_TOOLS_ZIP}"
  unzip -q "$tmp/cmdtools.zip" -d "$ANDROID_HOME/cmdline-tools"
  rm -rf "$ANDROID_HOME/cmdline-tools/latest"
  mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"
  rm -rf "$tmp"
else
  echo "    cmdline-tools already present, skipping download"
fi

export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

echo "==> [2/4] Android SDK packages (platform-tools, $COMPILE_SDK, $BUILD_TOOLS)"
yes | sdkmanager --licenses >/dev/null 2>&1 || true
sdkmanager "platform-tools" "$COMPILE_SDK" "$BUILD_TOOLS" >/dev/null

echo "==> [3/4] Dev signing keystore"
# The debug build type reuses the "release" signing config, so a keystore is
# required even for :app:assembleFullDebug.
if [ ! -f "keystore/apachiy.jks" ]; then
  bash scripts/sign-apachiy-apk.sh keystore
else
  echo "    keystore/apachiy.jks already present, skipping"
fi

echo "==> [4/4] local.properties (gitignored)"
if [ ! -f "local.properties" ]; then
  cat > local.properties <<EOF
# Auto-generated by .cursor/install.sh for the Cloud Agent dev environment.
# Gitignored. Do NOT commit real secrets here.

sdk.dir=$ANDROID_HOME

# Dev signing keystore (generated by scripts/sign-apachiy-apk.sh).
APACHIY_RELEASE_STORE_FILE=$REPO_ROOT/keystore/apachiy.jks
APACHIY_RELEASE_KEY_ALIAS=apachiy
APACHIY_RELEASE_KEY_PASSWORD=apachiy-dev
APACHIY_RELEASE_STORE_PASSWORD=apachiy-dev

# Backend config intentionally empty: the build succeeds with empty values,
# but cloud sync / auth features stay inert until real values are provided.
APACHIY_SUPABASE_URL=
APACHIY_SUPABASE_ANON_KEY=
APACHIY_API_BASE_URL=
APACHIY_TV_LOGIN_WEB_BASE_URL=

# Keep Dolby Vision native (libdovi/NDK/CMake) build off for a pure JVM build.
DOVI_NATIVE_ENABLED=false
USE_LOCAL_FFMPEG_DECODER=false
SENTRY_DSN=
EOF
else
  echo "    local.properties already present, leaving it untouched"
fi

# Convenience: expose ANDROID_HOME + SDK tools in interactive shells.
PROFILE="$HOME/.bashrc"
if [ -f "$PROFILE" ] && ! grep -q "ANDROID_HOME=$ANDROID_HOME" "$PROFILE"; then
  {
    echo ""
    echo "# Added by Apachiy TV .cursor/install.sh"
    echo "export ANDROID_HOME=\"$ANDROID_HOME\""
    echo "export ANDROID_SDK_ROOT=\"$ANDROID_HOME\""
    echo "export PATH=\"\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:\$PATH\""
  } >> "$PROFILE"
fi

echo "==> Warming Gradle dependency cache (:app:compileFullDebugKotlin)"
./gradlew --no-daemon :app:compileFullDebugKotlin -q || {
  echo "    (compile warm-up failed; dependencies may still be downloading — continuing)"
}

echo "==> Environment ready. Build with: ./gradlew :app:assembleFullDebug"
